@startuml
title PCIE Slave to Host Data Transfer Flowchart

start
:PCIE Slave Writes Data to DRAM Buffer;
:Update Write Pointer;
:PCIE Slave Sends MSI Interrupt to Host;
-> Host Receives MSI Interrupt;
:Host Reads Data from DRAM Buffer;
:Update Read Pointer;
:Host Checks for More Data (Read Pointer != Write Pointer);
alt More Data Available
    :Host Sends CCIF Interrupt to Slave;
    -> Slave Receives CCIF Interrupt;
    :Slave Checks for More Data to Send;
    alt More Data to Send
        goto start
    else No More Data to Send
        stop
    end
else No More Data Available
    stop
end
@enduml
