@startuml
title EMI Writer Sequence Diagram

participant EMIWriter
participant DRAMBuffer
participant PCIEHost

activate EMIWriter
EMIWriter -> DRAMBuffer: Initialize DRAM buffer
loop More data
    EMIWriter -> DRAMBuffer: Write data
    activate DRAMBuffer
    DRAMBuffer -->> EMIWriter: Update write pointer
    deactivate DRAMBuffer
    EMIWriter -> PCIEHost: Send MSI interrupt
    activate PCIEHost
    PCIEHost -->> EMIWriter: Receive CCIF interrupt
    deactivate PCIEHost
end
deactivate EMIWriter

@enduml
